apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace
  labels:
    app.kubernetes.io/name: paw
    app.kubernetes.io/component: workspace
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workspace
  labels:
    app.kubernetes.io/name: paw
    app.kubernetes.io/component: workspace
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workspace
  labels:
    app.kubernetes.io/name: paw
    app.kubernetes.io/component: workspace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workspace
subjects:
  - kind: ServiceAccount
    name: workspace
